### ISSUE TITLE
Wtyczka ULDK - działka na różnych arkuszach

### ISSUE THREAD

**Issue by bgisb** [gis-support/gis-support-plugin#1]
Dlaczego w QGIS korzystając z wyszukwarki ULDK nie dostaję geometrii działki 253/77?

QGIS 3.4.5
ULDK 1.9.2

Scenariusz:
1. Wyszukaj działkę w ULDK
Warmińsko-Mazurskie
Giżycki
Giżycko 2
Sulimy
działka 253/77
2. Otrzymamy komunikat " wybrana działka znajduje się na różnych arkuszach map. Wybierz jedną z nich".
3. W dropdownie dostaję 9x nazwę arkusza Sulimy
4. Niestety po wybraniu, któregokolwiek z arkuszy, nie dostaję geometrii działki.
![Sulimy](https://user-images.githubusercontent.com/48524622/65692522-01f1de80-e073-11e9-8f4d-e7bae3dda2c1.png)

Dodam, że korzystają z narzędzia identyfikacji, klikając na działkę 253/77, geometria zostaje zwrócona.
![sulimy_identyfikacja](https://user-images.githubusercontent.com/48524622/65692546-0a4a1980-e073-11e9-9e20-3855ffe0802d.png)

Jak wygląda wynik wyszukiwania teryt w geoportalu 280604_2.0015.253/77
![geoportal_sulimy](https://user-images.githubusercontent.com/48524622/65692563-10d89100-e073-11e9-9347-bd6f29c6f9a7.png)

**Comment by skowronskij** [comment]
Dziękujemy za zgłoszenie. W najnowszej wersji Wtyczki GIS Support opisany błąd został naprawiony i nie powinien już występować.
