### ISSUE TITLE
[Wyszukiwarka działek] Eksport nieznalezionych działek ewidencyjnych

### ISSUE THREAD

**Issue by bgisb** [gis-support/gis-support-plugin#10]
Propozycja dodania improvementu do Wtyczki GIS Support w narzędziu Wyszukiwarka działek ewidencyjnych z listy.

1. Korzystając z Wtyczki GIS Support 1.4 spróbuj wyszukać działki korzystając z pliku CSV 
[TERYT - Arkusz1_poprawiony.zip](https://github.com/gis-support/gis-support-plugin/files/4716141/TERYT.-.Arkusz1_poprawiony.zip)

2. Jedna z działek nie została odnaleziono. W załączonym pliku jest to tylko jedna działka, ale w przypadku dużych plików, może ich być zdecydowanie więcej.
![image](https://user-images.githubusercontent.com/48524622/83503990-38b2ab00-a4c4-11ea-8f3b-d760e4697583.png)

3. Aby nie kopiować ręcznie numerów teryt, proponujemy eksport do pliku CSV.

4. Po wybraniu przycisku "Zapisz nieznalezione", nastąpiłby eksport do pliku CSV
![image](https://user-images.githubusercontent.com/48524622/83504571-f047bd00-a4c4-11ea-8993-196d4a8f8651.png)

**Comment by gis-support** [comment]
Funkcjonalność pojawi się w nowym wydaniu Wtyczki GIS Support z dnia 16.06.2020
