### ISSUE TITLE
[Wyszukiwarka działek] Dodanie atrybutów do działek znalezionych na podstawie pliku CSV

### ISSUE THREAD

**Issue by bgisb** [gis-support/gis-support-plugin#11]
Korzystam z Wtyczki GIS Support (wersja 1.4) wraz z narzędziem Wyszukiwarka działek ewidencyjnych. Wyszukuję działki z listy w pliku CSV.

Po przetworzeniu listy działek z pliku CSV warstwa wynikowa mogłaby zawierać dane ewidencyjne wyszukanych działek (tak jest teraz) oraz dane oryginalne z pliku CSV dla każdej działki – w pliku CSV mogę mieć zapisane dodatkowe informacje np. o własności działki (prywatna/gminna) czy firmie dostarczającej światłowód. W ten sposób możnaby od razu na jednej warstwie, rozróżnić te działki np. innymi kolorami.

Plik CSV 
[TERYT - Arkusz1_poprawionyftth.zip](https://github.com/gis-support/gis-support-plugin/files/4716305/TERYT.-.Arkusz1_poprawionyftth.zip)
![image](https://user-images.githubusercontent.com/48524622/83506684-c774f700-a4c7-11ea-843c-510e29bbbbcc.png)
![image](https://user-images.githubusercontent.com/48524622/83506870-07d47500-a4c8-11ea-8d0d-6b1c0ae408f4.png)

**Comment by gis-support** [comment]
Funkcjonalność pojawi się w nowym wydaniu Wtyczki GIS Support z dnia 16.06.2020
