### ISSUE TITLE
[Wyszukiwarka działek] dla niektórych działek "-1 brak wyników"

### ISSUE THREAD

**Issue by bgisb** [gis-support/gis-support-plugin#12]
Wtyczka GIS Support 1.4 oraz 1.4.1

1. Spróbujcie wyszukać działkę pojedynczo:
Lubelskie
Lublin
Lublin
21-Osiedla Lsm
Numer działki: 5/1

2. Kliknij "Szukaj"

3. W efekcie pojawi się komunikat "Wtyczka ULDK: Nie znaleziono działki - odpowiedź serwera: '-1 brak wyników'"

Obserwacje: 
- W polu z pełnym numerem działki dostaniemy podpowiedź, że szukamy 066301_1.0021.5/1

- testowałam wyszukanie działki z linku http://uldk.gugik.gov.pl/service.php?obiekt=obreb&wynik=nazwa,teryt&teryt=066301_1.0021.5/1 tutaj wygląda, że działa

Pytanie dlaczego nie można wyszukać w QGIS? Co ciekawe, w  QGIS zadziała jak podam identyfikator działki w następującej fomie 066301_1.0021.AR_10.5/1 - czyli z frazą "AR".

**Comment by gis-support** [comment]
ULDK API nie ma możliwości listowania arkuszy map ewidencyjnych więc użytkownik sam musi podać tą wartość. Z tego co zauważyliśmy to niektóre powiaty zwracają listę działek (np. 300901_1.0001.47/2) i to wtyczka obsługuje poprzez wylistowanie arkuszy (chociaż aktualnie obręb się wyświetla).

@Hubz44 Do zrobienia:

1. Dodanie przy polu Numer działki ikony informacyjnej z treścią:
"Numer działki można podać z numerem arkusza mapy ewidencyjnej np. AR_1.2"
2. Poprawienie nazw wyświetlanych na liście arkuszy, powinny wyświetlać się numery arkuszy a nie nazwa obrębu. Przykładowy TERYT: 300901_1.0001.47/2
3. Jak wybiorę arkusz z listy to mam poniższy błąd, trzeba go poprawić:
```python
Traceback (most recent call last):
  File "/home/ppociask/.local/share/QGIS/QGIS3/profiles/wtyczka_gs/python/plugins/gissupport_plugin/modules/uldk/modules/teryt_search/main.py", line 275, in __search_from_sheet
    self.__handle_found([self.ui.combobox_sheet.currentData()])
  File "/home/ppociask/.local/share/QGIS/QGIS3/profiles/wtyczka_gs/python/plugins/gissupport_plugin/modules/uldk/modules/teryt_search/main.py", line 321, in __handle_found
    iface.messageBar().popWidget(self.message_bar_item)
RuntimeError: wrapped C/C++ object of type QgsMessageBarItem has been deleted
```

**Comment by bgisb** [comment]
Jasne, czyli w przypadku przykładu działki w Lublinie, użytkownik powinien sam znać arkusz mapy ewidencyjnej. Wystarczy, że wybierając działkę pojedynczo z listy: Lubelskie, Lublin, Lublin, 21-Osiedla Lsm...uzupełnię numer działki wraz z numerem arkusza **AR_8.5/1**

Przetestowałam usprawnienia w wersji testowej wtyczki 1.4.3.
1. Tootip przy numerze działki jest informacją, że możemy podać numer arkusza oraz po kropce numer działki - "Numer działki można podać z numerem arkusza mapy ewidencyjnej np. AR_1.2" np. AR_8.5/1, gdzie AR_8 to numer arkusza, a 5/1 to numer działki.
2. Po wpisaniu terytu "TERYT: 300901_1.0001.47/2" dostaję oczekiwany komunikat:
"Wtyczka ULDK: Wybrana działka znajduje się na różnych arkuszach map. Wybierz z listy jedną z nich.". Mogę wybrać arkusz z rozwijanej listy i otrzymać geometrię działki.
