### ISSUE TITLE
QGIS często się zawiesza lub przestaje działać

### ISSUE THREAD

**Issue by neilpylak** [gis-support/gis-support-plugin#14]
Po zainstalowaniu wtyczki GIS Support ver. 1.5 na QGIS version: 3.14.0-Pi (Mac) w trybie identyfikacji działek ULDK (po klikaniu na wyszukiwane działki), QGIS przestaje działać. Podobny problem jest na Windowsie, przy czym tu QGIS się zawiesza, w skrajnych przypadkach wymagany jest restart komputera.

**Comment by gis-support** [comment]
Dziękujemy za zgłoszenie. Zweryfikujemy nakreślony powyżej scenariusz. Proszę o informację, na terenie jakiego powiatu próbował Pan dokonać identyfikacji działek ULDK?

**Comment by neilpylak** [comment]
Powiat biłgorajski
gmina wiejska Biłgoraj 
Okręg Gromada
Działka 308, 309, 310 (dwie ostatnie za pomocą narzędzia identyfikacji działek). 

Pozdrawiam, 
KP

**Comment by gis-support** [comment]
Główny Urząd Geodezji i Kartografii zajmuje się integracją danych z powiatów: część powiatów przekazuje do GUGiK dane z których wystawiane są usługi, a część tylko przekazuje dostęp do usługi, którą świadczy zewnętrzna firma.

W przypadku powiatu biłgorajskiego, proszę zwrócić uwagę na rozbieżność, pomiędzy danymi WMS EGIB publikowanym z powiatu, a geometrią działek, jaka jest zwracana po kliknięciu na mapę. Niestety nie wszystkie powiaty są na tyle sprawne, aby publikować geometrię działek. 

Korzystając z narzędzia identyfikacji działek, dostajemy geometrię działek 308, 309, 310, ale tylko dlatego, że działki zostały uzupełnione z LPIS (dane historyczne). Nie dostajemy geometrii działki, która jest publikowana na WMS z danych powiatowych.
![image](https://user-images.githubusercontent.com/10209250/89887483-a965fa00-dbce-11ea-9b0f-f7af46c47336.png)

Proszę zobaczyć jak wygląda geometria działki 310, na tle działek uzupełnionych z LPIS:
![image](https://user-images.githubusercontent.com/10209250/89887553-d1555d80-dbce-11ea-885c-55ee581374c3.png)

![image](https://user-images.githubusercontent.com/10209250/89887607-e500c400-dbce-11ea-8aa9-19f382abd7e8.png)

Bardzo możliwe, że integrator danych, nałożył limit na identyfikację i tym samym otrzymywanie geometrii działki, która pojawia się jako "uzupełnienie LPIS". Przekroczenie limitu powoduje "zawieszenie się QGIS".
![image](https://user-images.githubusercontent.com/10209250/89887709-11b4db80-dbcf-11ea-9762-c441f01c0c03.png)

Podaję link do wprawdzie leciwego już artykułu, ale również traktującego o powiatach, które mają problem z danymi [](https://gis-support.pl/co-sie-stalo-z-danymi-lpis/)

**Comment by gis-support** [comment]
Dzień dobry, proszę zaktualizować **Wtyczkę GIS Support do wersji 1.6**, gdzie wdrożyliśmy poprawkę usprawniającą identyfikację działek (klikanie na szukane działki). Wcześniej wykryliśmy problem na Windows7. 

Proszę o informację, czy po aktualizacji, problem z "zawieszaniem się" ustąpił?

**Comment by gis-support** [comment]
Z uwagi na brak aktywności zamykam zgłoszenie. Zakładam, że brak odpowiedzi oznacza, że problem ustąpił po aktualizacji Wtyczki GIS Support.
