### ISSUE TITLE
Obliczanie wysokości dla zaznaczonej warstwy liniowej zamiast ręcznego rysowania :)

### ISSUE THREAD

**Issue by kapiwko** [gis-support/gis-support-plugin#15]
Fajnie by było jakby nie trzeba było ręcznie rysować trasy tylko po prostu zaznaczyć wcześniej przygotowaną warstwę :)

**Comment by gis-support** [comment]
Dzięki za podsunięcie pomysłu, póki co jednak nie mamy takiej funkcjonalności na roadmapie. Zwracamy jednak uwagę, że potrzebna byłaby walidacja danych dla linii z rozgałęzieniami. Co w przypadku wielolinii?  Zależy nam, aby narzędzie było spójne i możliwie proste dla dużej grupy użytkowników, stąd trzymamy się obecnego kształtu narzędzia.
![NMT_GIS_Support](https://user-images.githubusercontent.com/10209250/116976528-94337d00-acc1-11eb-8540-d443fc72a31a.png)
