### ISSUE TITLE
Wyszukiwanie działek ewidencyjnych - zamykanie programu podczas przerywania pobierania danych

### ISSUE THREAD

**Issue by geoyolog** [gis-support/gis-support-plugin#17]
dzień dobry, podczas pobierania działek ewidencyjnych (Identyfikacja ULDK - z warstwy) często się zdarza, że próbując przerwać pobieranie, wtyczka zamyka program a wszystkie pobrane [?] dane są tracone. W przypadku potrzeby pomocy przy diagnostyce, proszę o kontakt

**Comment by gis-support** [comment]
Dziękujemy za zgłoszenie.

Na jakiej wersji QGIS i systemie operacyjnym pojawia się problem ze stabilnością aplikacji?

**Comment by gis-support** [comment]
Ze względu na brak odpowiedzi zamykamy to zgłoszenie. W przypadku nowych informacji proszę je otworzyć lub stworzyć nowe.
