### ISSUE TITLE
Wyszukiwanie w Krajowej Integracji Numeracji Adresowej

### ISSUE THREAD

**Issue by s10th** [gis-support/gis-support-plugin#21]
Python zgłasza błąd 500 dla URL.
Zmiana url w "gissupport_plugin\modules\wms\services.json"
z "https://integracja.gugik.gov.pl/cgi-bin/KrajowaIntegracjaNumeracjiAdresowej"
na "https://mapy.geoportal.gov.pl/wss/ext/KrajowaIntegracjaNumeracjiAdresowej" załatwia sprawę.

**Comment by gis-support** [comment]
Dziękujemy za zgłoszenie.
Jesteśmy w trakcie weryfikacji adresów używanych usług, po zakończeniu zostanie wydana nowa wersja wtyczki z poprawionymi danymi.
