### ISSUE TITLE
Nie ładują się warstwy cieniowania i hipsometrii z Narzędzia do szybkiego ładowania WMTS

### ISSUE THREAD

**Issue by kambe507** [gis-support/gis-support-plugin#30]
Od jakiegoś czasu nie ładują mi się warstwy hipsometrii i cieniowania z narzędzia do szybkiego ładowania. Otrzymuję nastepujący komunikat:

![image](https://github.com/gis-support/gis-support-plugin/assets/82141736/799f078f-d49a-43f4-8f0c-3094dec650a1)

Pozostałe serwisy ładują się bez problemów.

**Comment by kambe507** [comment]
Serwisy wms/wmts powinny mieć w adresie uwzględnione polecenie Service=WMTS oraz Request=GetCapabilities. Szczegóły na stronie https://www.geoportal.gov.pl/pl/usluga/uslugi-przegladania-wms-i-wmts/. 
Być może to jest przyczyną problemu.

**Comment by bgisb** [comment]
Dziękujemy za zgłoszenie. Problem został już namierzony – poprawka, będzie dostępna w nadchodzącej aktualizacji Wtyczki GIS Support. Planujemy wydanie na drugą połowę września. 

Damy znać, kiedy nowe wydanie będzie już dostępne!

**Comment by bgisb** [comment]
Cześć,

Chciałam poinformować, że wtyczka GIS Support w wersji 2.4 jest już dostępna. Prosimy o jej zaktualizowanie i przetestowanie działania. WMTS z Cieniowaniem i hipsometrią jest już dostępny!

![Uploading cieniowanie_hipsometria.png…]()
