### ISSUE TITLE
ładowanie wtyczki przy braku dostępu do internetu

### ISSUE THREAD

**Issue by PawelKra** [gis-support/gis-support-plugin#31]
W dzisiejszych czasach nie do pomyślenia ale czasem jednak nie ma dostępu do internetu ;)

<img width="1271" alt="Screenshot 2024-06-29 at 17 43 50" src="https://github.com/gis-support/gis-support-plugin/assets/15887575/85ae0ff3-6109-4624-9e61-517bfab29774">

**Comment by bgisb** [comment]
To prawda, mamy jednak dobrą wiadomość – poprawka, będzie dostępna w nadchodzącej aktualizacji Wtyczki GIS Support. Planujemy ją wypuścić w drugiej połowie września. Damy znać, kiedy nowe wydanie będzie już dostępne!

**Comment by bgisb** [comment]
Cześć,

Chciałam poinformować, że **Wtyczka GIS Support w wersji 2.4** jest już dostępna. Prosimy o jej zaktualizowanie i przetestowanie działania. Będziemy wdzięczni za informację zwrotną, czy problem, o którym wspominałeś, nadal występuje, czy też został rozwiązany po aktualizacji.

Dziękujemy za współpracę i czekamy na Twoją odpowiedź.
