### ISSUE TITLE
nie działająca wtyczka i error przy uruchomieniu Qgis

### ISSUE THREAD

**Issue by janmajewski1993** [gis-support/gis-support-plugin#47]
Od kliku godzin przy próbie uruchomienia Qgis'a i wczytaniu wtyczki pojawia się załączony komunikat:
![error](https://github.com/user-attachments/assets/3281cb13-3562-472d-aa9f-5b7bb3f89e89)

**Comment by bgisb** [comment]
Cześć,

Czy problem, o którym wspominałeś, nadal występuje? Chcielibyśmy również upewnić się, czy korzystasz z wtyczki GIS Support w wersji 2.4. W tej wersji dodaliśmy poprawkę dotyczącą ładowania wtyczki w sytuacjach, gdy brak jest dostępu do internetu. Aktualizacja może rozwiązać napotkany problem, jeśli przyczyną jest chwilowy brak połączenia z siecią.

Prosimy o informację, czy problem się powtarza po zaktualizowaniu wtyczki.

**Comment by janmajewski1993** [comment]
Problem ustąpił dnia następnego.
Pozdrawiam.


czw., 10 paź 2024, 21:47 użytkownik bgisb ***@***.***>
napisał:
