### ISSUE TITLE
ortofotomapa standardowa w niewłaściwym układzie współrzędnych

### ISSUE THREAD

**Issue by kambe507** [gis-support/gis-support-plugin#49]
Za pomocą "Narzędzia do szybkiego wczytywania WMTS" dodaję Ortofotomapę standardową i okazuje się, że mapa "nie siedzi" we właściwym układzie współrzędnych. Pozostałe serwisy są poprawnie. Również dodanie tej ortofotomapy poprzez adres wms działa poprawnie. 
Na załączonych zrzutach: 
1. poprawnie:
![image](https://github.com/user-attachments/assets/90c5cc18-4dd7-4f9f-a465-e2c36d2b7b06)

2. nie poprawnie: "Narzędzia do szybkiego wczytywania WMTS" > "Ortofotomapa standardowa"
![image](https://github.com/user-attachments/assets/cb9a14a8-e12c-4448-af0d-f7c9cee1a7c0)

przesunięcie jest około 1 km w linii prostej.

**Comment by bgisb** [comment]
Cześć,

Dziękujemy za przesłane informacje, jednak na ich podstawie trudno jest jednoznacznie zidentyfikować przyczynę problemu. Prosimy o przygotowanie nagrania, w którym pokażesz cały proces dodawania ortofotomapy, ze szczególnym uwzględnieniem:

**Układu współrzędnych projektu** – zwróć uwagę, jaki układ jest ustawiony w Twoim projekcie QGIS.
Wersji wtyczki GIS Support – upewnij się, że korzystasz z najnowszej wersji wtyczki (2.4)

Warto również referencyjnie wyświetlić podkład z OpenStreetMap. Dzięki temu będziesz mógł łatwiej zweryfikować, czy ortofotomapa jest wyświetlana we właściwym miejscu względem innych warstw i danych geograficznych. Podkład z OSM często pomaga szybko ocenić, czy problem leży po stronie układu współrzędnych, czy może dotyczy samego serwisu WMTS.

Dla porównania, poniżej załączamy nagranie z naszej demonstracji, w którym widać, że wczytywana ortofotomapa standardowa poprzez wtyczkę GIS Support wyświetla się prawidłowo. 


https://github.com/user-attachments/assets/c0c447ab-7b2e-4559-ad5c-f05633af0e05


Mamy nadzieję, że to pomoże w zidentyfikowaniu różnic i szybszym rozwiązaniu problemu.
