### ISSUE TITLE
Baza WMS - KIUT layer without transparency

### ISSUE THREAD

**Issue by bgisb** [gis-support/gis-support-plugin#5]
Please check the issue with the transparency of KIUT layer.

QGIS: 3.10.2-A Coruña
GIS Support Plugin: 1.2.5

1. Add "Sieć telekomunikacyjna"
![image](https://user-images.githubusercontent.com/48524622/74539434-502e4e00-4f3e-11ea-902a-1dd7b2b92bf9.png)

2. Zoom to "Stary Broniszew, gmina Mykanów, powiat częstochowski, Silesian Voivodeship, 42-231, Poland"

3. Check visibility of "Sieć telekomunikacyjna"
![image](https://user-images.githubusercontent.com/48524622/74539811-f417f980-4f3e-11ea-8e98-705f0debfe95.png)

![image](https://user-images.githubusercontent.com/48524622/74539838-02661580-4f3f-11ea-83fc-ac8ce8008c45.png)

The same layer, just added by native QGIS tool - expected behavior - layer without white background 
![image](https://user-images.githubusercontent.com/48524622/74540182-9cc65900-4f3f-11ea-9827-7af5b816e51a.png)

**Comment by gis-support** [comment]
Thank you for your feedback. Currently all WMS layers are added as image/jpeg so there is no option for transparency. In near future we're planning to add list of available formats so user can choose image/png with transparent background.

**Comment by gis-support** [comment]
We add option for choosing format in version 1.3. If layer has transparency then you should load it as PNG (this is default format)
