### ISSUE TITLE
Niewyszukiwanie działek ewid po poligonie

### ISSUE THREAD

**Issue by 90tomaszko** [gis-support/gis-support-plugin#51]
Cześć,
nie wyszukuje działek ewidencyjnych po warstwie poligonowej - po kliknięciu Start jest cały czas "Trwa wyszukiwanie 1 obiektów...." 

![image](https://github.com/user-attachments/assets/c74996d5-39c9-44d1-a96d-99a1e27bf49d)

Przy wybraniu warstwy liniowej działa bez problemu, ale są to tylko działki które przecinają się z linią, dlatego brakuje sporo działek wewnątrz obszaru określonego linią zamkniętą.

**Comment by 90tomaszko** [comment]
Wszystko najnowsze - QGis 3.38.3 i GIS Support 2.4.
Podążyłem temat i w jednym pliku zrobiłem 4 różne powierzchnie, dla 3 mniejszych generuje działki, ale jak się przekroczy pewną powierzchnię (chyba 10 000 m2) wtyczka GIS support się zawiesza i jest ciągle "Trwa wyszukiwanie 1 obiektu"

![image](https://github.com/user-attachments/assets/92c91f12-b5b2-4a76-b4ae-df342434e6f2)
[warstwy.zip](https://github.com/user-attachments/files/17349726/warstwy.zip)

**Comment by 90tomaszko** [comment]
Może to coś komuś pomoże przy rozwiązaniu błędu....

![image](https://github.com/user-attachments/assets/a31c055c-4c97-436b-b0b2-3ac59781ac38)

**Comment by gis-support** [comment]
Naprawiono w https://github.com/gis-support/gis-support-plugin/pull/60. Poprawka będzie dostępna w kolejnej wersji wtyczki.
