### ISSUE TITLE
Nie pobiera wysokości

### ISSUE THREAD

**Issue by zmarekz** [gis-support/gis-support-plugin#7]
Wtyczka przestała wpisywać wysokość dla punktów. Nie wpisuje wartości wysokości a jedynie tworzy kolejną kolumnę w tabeli. Nie potrafi zaktualizować danych w już istniejącej tabeli. Qgis 3.4.15-Madeira
Pozdrawiam

**Comment by michaldrozdz** [comment]
Działało, działało i przestało? Wygląda jak ban z GUGiK. Czy wyszukiwarka działek działa prawidłowo?

**Comment by zmarekz** [comment]
Wyszukiwarka działek działa prawidłowo. Ban chyba nie możliwy bo jak użyje "celownika" wyznacz wysokość w nowym punkcie to wówczas bez problemu pokazuje mi wysokość. Wygenerowałem sobie siatkę punktów co 5m i chciałem utworzyć coś jakby mapę hipsometryczną. Dla odległości co 50m pare dni temu działało. Dziś już też nie. 
Pozdrawiam

**Comment by skowronskij** [comment]
@zmarekz można prosić o informacje odnośnie układu współrzędnych warstwy i projektu?

**Comment by zmarekz** [comment]
Warstwy i projektu jest ten sam.
Układ współrzędnych
EPSG:2176 - ETRS89 / Poland CS2000 zone 5 - Odwzorowany

**Comment by skowronskij** [comment]
Niestety błędu nie mogę odtworzyć. Udało mi się pobrać wysokości dla reguralnej siatki punktów w odstępach co 50m w układzie 2176. Możliwe, że rzeczywiście jakieś ograniczenia od GUGiK. 
Proszę o sprawdzenie dwóch pierwszych przykładów na stronie usługi - https://services.gugik.gov.pl/nmt/. Jeśli któryś z nich nie działa prawidłowo, oznacza to, że Pana dostęp do usługi został ograniczony. W przeciwnym razie będę dalej starał się odtworzyć błąd i go naprawić.

**Comment by zmarekz** [comment]
ok wrócę do tematu w poniedziałek teraz niestety inne obowiązki ;)

**Comment by zmarekz** [comment]
Nie dawało mi to spokoju i sprawdziłem jeszcze dziś oba działają. 
Poczekajmy do przyszłego tygodnia może to jakiś tymczasowy błąd. ;)

**Comment by zmarekz** [comment]
Witam ponownie
Wiem już kiedy błąd występuje (przynajmniej u mnie).
A więc tworze sobie siatkę punktów Wektor - Narzędzia badawcze - utwórz siatkę - ok siatka utworzona jako prostokąt a pod nim miasto (ok 2mln punktów co 5m). Przycinam siatkę punktów do granic miasta - Wektor - narzędzia geoprocesingu - iloczyn (jako - i punkty są już tylko w granicach miasta.  
Przed wykonaniem iloczynu wysokość dodawana jest raczej bez problemu tak po Iloczynie już nie.

**Comment by gis-support** [comment]
Udało nam się powtórzyć błąd według podanego scenariusz tj.
1. Stwórz siatkę punktów (testowaliśmy na 25 punktach), układ współ. 2176
2. Wykonaj iloczyn z warstwą powierzchniową
3. Spróbuj rozszerzyć warstwę "Iloczyn" o wysokość punktów
>>>Tworzy się nowa kolumna nmt_wys z pustymi wartościami

Kiedy jednak spróbujemy wygenerować wysokość dla punktów z warstwy "Siatka" nie ma żadnego problemu.

**Comment by gis-support** [comment]
Problem dotyczy warstw z geometriami wieloczęściowymi. Niestety wtyczka wymaga aby były to proste, pojedyncze elementy.
@Hubz44 W metodzie [extendLayerByHeight ](https://github.com/gis-support/gis-support-plugin/blob/master/gissupport_plugin/modules/gugik_nmt/gui/gugik_nmt_plugin_dockwidget.py#L196) trzeba dodać sprawdzenie czy warstwa jest wieloczęściowa, jeśli tak to wyświetlić komunikat informujący o tym i przerwać działanie.

**Comment by gis-support** [comment]
@Hubz44 

1. W metodzie [createNewField](https://github.com/gis-support/gis-support-plugin/blob/master/gissupport_plugin/modules/gugik_nmt/gui/gugik_nmt_plugin_dockwidget.py#L186) zmień [layer.reload()](https://github.com/gis-support/gis-support-plugin/blob/master/gissupport_plugin/modules/gugik_nmt/gui/gugik_nmt_plugin_dockwidget.py#L191) na `layer.updateFields()`.

2. Załączam warstwę, na której aktualne rozwiązanie nie zadziała. Są w niej 3 punkty, z czego dwa są geometriami wieloczęściowymi, ale posiadającymi 1 część, więc sprawdzenie `num_geometries($geometry) > 1` nie zadziała dla nich. Ale z punktu widzenia wtyczki są to poprawne przypadki tzn. możliwe jest pobranie dla nich wysokości. Problem jest w metodzie [transformGeometry](https://github.com/gis-support/gis-support-plugin/blob/master/gissupport_plugin/modules/gugik_nmt/gui/gugik_nmt_plugin_dockwidget.py#L173), w której używana jest metoda `asPoint()`, a ona dla obiektów wieloczęściowych (nawet jeśli mają jedną część) nie zadziała. Można to prosto obejść w ten sposób:
```python
point = geometry.asGeometryCollection()[0].asPoint()
```
[test.geojson.zip](https://github.com/gis-support/gis-support-plugin/files/4791775/test.geojson.zip)
